Repository Strayker-Software/Binder, pull requests merged in 2023-03, with the labels that each got.

#41 feat: Added global handling middleware
  binder-backend/Binder.Api/Program.cs
  binder-backend/Binder.Application/Binder.Application.csproj
  binder-backend/Binder.Application/Services/Middleware/CustomExceptions/NotFoundException.cs
  binder-backend/Binder.Application/Services/Middleware/ErrorHandlingMiddleware.cs
  binder-backend/Binder.Core/ExceptionConstants.cs
Labels: feature

#44 feat: Add ci pipeline
  .github/workflows/pull-request.yml
Labels: feature

#51 Add Prettier to Web Frontend
  binder-web-frontend/.husky/pre-commit
  binder-web-frontend/.prettierrc.json
  binder-web-frontend/package-lock.json
  binder-web-frontend/package.json
  binder-web-frontend/src/app/app-routing.module.ts
  binder-web-frontend/src/app/app.component.html
  binder-web-frontend/src/app/app.component.ts
  binder-web-frontend/src/app/app.module.ts
  binder-web-frontend/src/environments/environment.prod.ts
  binder-web-frontend/src/environments/environment.ts
  binder-web-frontend/src/index.html
  binder-web-frontend/src/main.ts
  binder-web-frontend/src/pages/home/home.component.html
  binder-web-frontend/src/pages/home/home.component.ts
  binder-web-frontend/src/pages/pages.module.ts
  binder-web-frontend/src/polyfills.ts
  binder-web-frontend/src/shared/shared.module.ts
  binder-web-frontend/src/styles.scss
Labels: feature

#50 docs: Remove old docs files
  docs/.gitkeep
  docs/CONTRIBUTORS.md
  docs/README.md
  docs/en/README.md
  docs/en/user/README.md
  docs/en/user/add-task-dialog.png
  docs/en/user/add-task-final.png
  docs/en/user/add-task-menu.png
  docs/en/user/delete-category.png
  docs/en/user/delete-task-menu.png
  docs/en/user/edit-task-dialog.png
  docs/en/user/edit-task-menu.png
  docs/en/user/new-category-added.png
  docs/en/user/new-category-name.png
  docs/en/user/new-category.png
  docs/en/user/save.png
  docs/en/user/show-hide-completed-category.png
  docs/pl/README.md
  docs/pl/user/README.md
  docs/pl/user/add-task-dialog.png
  docs/pl/user/add-task-final.png
  docs/pl/user/add-task-menu.png
  docs/pl/user/delete-category.png
  docs/pl/user/delete-task-menu.png
  docs/pl/user/edit-task-dialog.png
  docs/pl/user/edit-task-menu.png
  docs/pl/user/new-category-added.png
  docs/pl/user/new-category-name.png
  docs/pl/user/new-category.png
  docs/pl/user/save.png
  docs/pl/user/show-hide-completed-category.png
Labels: bug, documentation

#53 Update Angular to v15
  .github/workflows/pull-request.yml
  binder-web-frontend/.browserslistrc
  binder-web-frontend/package-lock.json
  binder-web-frontend/package.json
  binder-web-frontend/src/styles.scss
  binder-web-frontend/tsconfig.json
Labels: refactor

#47 Feature create tables list #16
  binder-web-frontend/src/pages/home/components/tables-list/tables-list.component.html
  binder-web-frontend/src/pages/home/components/tables-list/tables-list.component.scss
  binder-web-frontend/src/pages/home/components/tables-list/tables-list.component.ts
  binder-web-frontend/src/pages/pages.module.ts
  binder-web-frontend/src/styles.scss
Labels: feature

#42 feat: add app navbar wihout logic
  binder-web-frontend/src/pages/home/components/navbar/navbar.component.html
  binder-web-frontend/src/pages/home/components/navbar/navbar.component.scss
  binder-web-frontend/src/pages/home/components/navbar/navbar.component.ts
  binder-web-frontend/src/pages/pages.module.ts
Labels: feature
