Repository Strayker-Software/Binder, pull requests merged in 2023-12, with the labels that each got.

#136 Adjust PR Template
  .github/pull_request_template.md
Labels: documentation, refactor

#139 Change issue templates to be more robust
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/env_issue_template.md
  .github/ISSUE_TEMPLATE/environment_issue.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/refactor_request.md
  .github/ISSUE_TEMPLATE/test_request.md
Labels: documentation, refactor

#138 Swap MatAccordion to MatTree in Tables List component
  binder-web-backend/Binder.Api/Properties/launchSettings.json
  binder-web-frontend/src/pages/home/components/tables-list/tables-list.component.html
  binder-web-frontend/src/pages/home/components/tables-list/tables-list.component.scss
  binder-web-frontend/src/pages/home/components/tables-list/tables-list.component.ts
  binder-web-frontend/src/pages/pages.module.ts
  binder-web-frontend/src/shared/models/tableFlatNode.ts
  binder-web-frontend/src/shared/models/tableNode.ts
Labels: refactor

#135 Setup SCP-based Deploy Pipeline
  .github/workflows/ci.yml
  .github/workflows/deploy.yml
Labels: feature

#140 AutoMapper Setup
  .github/workflows/deploy.yml
  binder-web-backend/Binder.Api/Binder.Api.csproj
  binder-web-backend/Binder.Api/Extensions/AddMappingExtensions.cs
  binder-web-backend/Binder.Api/Extensions/SwaggerServiceExtensions.cs
  binder-web-backend/Binder.Api/Mappings/DtoToCoreModelsMappingsProfile.cs
  binder-web-backend/Binder.Api/Program.cs
  binder-web-backend/Binder.Application/Services/Middleware/ErrorHandlingMiddleware.cs
  binder-web-backend/Binder.Core/Models/ToDoTask.cs
  binder-web-backend/Binder.Persistence/Binder.Persistence.csproj
  binder-web-backend/Binder.Persistence/Mappings/PDtoToCoreModelsMappingsProfile.cs
  binder-web-frontend/src/pages/home/components/tables-list/tables-list.component.scss
Labels: feature

#143 refactor(webbackend): Refactor exception's handler
  binder-web-backend/Binder.Application/Services/Middleware/ErrorHandlingMiddleware.cs
  binder-web-backend/Binder.Application/Services/Middleware/GetProblemDetailsByExceptionFactory.cs
Labels: refactor
