Repository Strayker-Software/Binder, pull requests merged in 2023-11, with the labels that each got.

#102 Repair warning message on Web Frontend start
  binder-web-frontend/angular.json
Labels: bug

#116 Fix issue templates bugs
  .github/ISSUE_TEMPLATE/env_issue_template.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/refactor_request.md
  .github/ISSUE_TEMPLATE/test_request.md
Labels: bug

#117 Implement Project's Logo
  LICENSE-DISCLAIMER.md
  binder-web-frontend/src/assets/images/.gitkeep
  binder-web-frontend/src/assets/images/favicon.ico
  binder-web-frontend/src/index.html
  binder-web-frontend/src/pages/home/components/table-view/table-view.component.ts
  docs/logo/100x92.jpg
  docs/logo/1024x945.jpg
  docs/logo/1271x1173.jpg
  docs/logo/150x150.jpg
  docs/logo/240x221.jpg
  docs/logo/320x295.jpg
  docs/logo/400x369.jpg
  docs/logo/500x461.jpg
  docs/logo/640x591.jpg
  docs/logo/75x75.jpg
  docs/logo/800x738.jpg
  docs/logo/original.jpg
Labels: feature

#120 Update repo's ReadMe with new data
  README.md
  docs/mockup.png
Labels: bug, documentation

#123 Add MainSpace Component
  binder-web-frontend/src/app/app.component.scss
  binder-web-frontend/src/pages/home/components/main-space/main-space.component.html
  binder-web-frontend/src/pages/home/components/main-space/main-space.component.scss
  binder-web-frontend/src/pages/home/components/main-space/main-space.component.ts
  binder-web-frontend/src/pages/home/components/navbar/navbar.component.html
  binder-web-frontend/src/pages/home/components/navbar/navbar.component.scss
  binder-web-frontend/src/pages/home/components/side-panel/side-panel.component.scss
  binder-web-frontend/src/pages/home/components/table-view/table-view.component.html
  binder-web-frontend/src/pages/home/components/table-view/table-view.component.scss
  binder-web-frontend/src/pages/home/components/tables-list/tables-list.component.html
  binder-web-frontend/src/pages/home/home.component.html
  binder-web-frontend/src/pages/home/home.component.scss
  binder-web-frontend/src/pages/pages.module.ts
Labels: feature

#121 Add Docker containers for Web Frontend and Web Backend
  .github/ISSUE_TEMPLATE/env_issue_template.md
  binder-web-backend/Binder.Api/appsettings.Docker.json
  binder-web-backend/Dockerfile
  binder-web-frontend/Dockerfile
  docker-compose.yml
Labels: feature

#129 Error message is not appearing in web browser
  binder-web-backend/Binder.Application/Services/Middleware/ErrorHandlingMiddleware.cs
  binder-web-backend/Binder.Application/Services/ToDoTasksService.cs
  binder-web-backend/Binder.Persistence/Repositories/ToDoTasksRepository.cs
Labels: bug

#131 Make every suitable class sealed
  binder-web-backend/Binder.Api/Controllers/AppVersionsController.cs
  binder-web-backend/Binder.Api/Controllers/TablesController.cs
  binder-web-backend/Binder.Api/Controllers/ToDoTasksController.cs
  binder-web-backend/Binder.Application/Services/AppVersionService.cs
  binder-web-backend/Binder.Application/Services/DefaultTableService.cs
  binder-web-backend/Binder.Application/Services/Middleware/CustomExceptions/NotFoundException.cs
  binder-web-backend/Binder.Application/Services/Middleware/ErrorHandlingMiddleware.cs
  binder-web-backend/Binder.Application/Services/ToDoTasksService.cs
  binder-web-backend/Binder.UnitTests/Repositories/DefaultTableRepositoryTests.cs
  binder-web-backend/Binder.UnitTests/Services/DefaultTableServiceTests.cs
Labels: refactor

#132 Make all controllers declarations unified
  binder-web-backend/Binder.Api/Controllers/AppVersionsController.cs
  binder-web-backend/Binder.Api/Controllers/TablesController.cs
  binder-web-backend/Binder.Api/Controllers/ToDoTasksController.cs
  binder-web-frontend/src/api/api/appVersions.service.ts
  binder-web-frontend/src/api/api/tables.service.ts
  binder-web-frontend/src/api/api/toDoTasks.service.ts
  binder-web-frontend/src/pages/home/components/header/header.component.ts
  binder-web-frontend/src/pages/home/components/table-view/table-view.component.ts
  binder-web-frontend/src/pages/home/components/tables-list/tables-list.component.ts
Labels: refactor

#133 Ioc container setup code
  binder-web-backend/Binder.Api/Extensions/SwaggerServiceExtensions.cs
  binder-web-backend/Binder.Api/Program.cs
  binder-web-backend/Binder.Application/Extensions/ApplicationServices.cs
  binder-web-backend/Binder.Persistence/Extensions/PersistenceServices.cs
Labels: refactor
