Repository Strayker-Software/Binder, pull requests merged in 2023-10, with the labels that each got.

#63 Create App's Domain Buttons
  binder-web-frontend/src/pages/home/components/domain-buttons/domain-buttons.component.html
  binder-web-frontend/src/pages/home/components/domain-buttons/domain-buttons.component.scss
  binder-web-frontend/src/pages/home/components/domain-buttons/domain-buttons.component.ts
  binder-web-frontend/src/pages/home/home.component.html
  binder-web-frontend/src/pages/pages.module.ts
Labels: feature

#62 Add OpenAPI Generator and fix package conflicts
  binder-web-frontend/package-lock.json
  binder-web-frontend/package.json
Labels: feature

#69 Change URL of OpenAPI specs in generator's command
  binder-web-frontend/openapitools.json
  binder-web-frontend/package.json
Labels: bug

#64 Feature/18 create apps header
  binder-web-frontend/src/pages/home/components/header/header.component.html
  binder-web-frontend/src/pages/home/components/header/header.component.scss
  binder-web-frontend/src/pages/home/components/header/header.component.ts
  binder-web-frontend/src/pages/home/home.component.html
  binder-web-frontend/src/pages/home/home.component.scss
  binder-web-frontend/src/pages/pages.module.ts
Labels: feature

#72 Hotfix/49 fix some data in issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/env_issue_template.md
  .github/ISSUE_TEMPLATE/feature-request.md
Labels: bug, documentation

#71 Connect Web Backend to Web Frontend with OpenAPI Generator
  binder-web-backend/Binder.Api/Constants/WebApiIocConfigValues.cs
  binder-web-backend/Binder.Api/Program.cs
  binder-web-backend/Binder.Api/Properties/launchSettings.json
  binder-web-backend/Binder.Api/appsettings.Development.json
  binder-web-frontend/src/api/.gitignore
  binder-web-frontend/src/api/.gitkeep
  binder-web-frontend/src/api/.openapi-generator-ignore
  binder-web-frontend/src/api/.openapi-generator/FILES
  binder-web-frontend/src/api/.openapi-generator/VERSION
  binder-web-frontend/src/api/README.md
  binder-web-frontend/src/api/api.module.ts
  binder-web-frontend/src/api/api/api.ts
  binder-web-frontend/src/api/api/defaultTable.service.ts
  binder-web-frontend/src/api/configuration.ts
  binder-web-frontend/src/api/encoder.ts
  binder-web-frontend/src/api/git_push.sh
  binder-web-frontend/src/api/index.ts
  binder-web-frontend/src/api/model/models.ts
  binder-web-frontend/src/api/model/toDoTask.ts
  binder-web-frontend/src/api/param.ts
  binder-web-frontend/src/api/variables.ts
  binder-web-frontend/src/app/app.module.ts
  binder-web-frontend/src/pages/home/components/domain-buttons/domain-buttons.component.scss
  binder-web-frontend/src/pages/home/components/domain-buttons/domain-buttons.component.ts
  binder-web-frontend/src/pages/home/components/table-view/table-view.component.html
  binder-web-frontend/src/pages/home/components/table-view/table-view.component.ts
  binder-web-frontend/src/pages/pages.module.ts
  binder-web-frontend/src/shared/models/DisplayableTask.ts
  binder-web-frontend/src/shared/models/ToDoTask.ts
Labels: feature

#73 fix(webfrontend): Add pointer on hover over navbar buttons
  binder-web-frontend/src/pages/home/components/navbar/navbar.component.scss
Labels: bug

#74 fix(webfrontend): Fix Dark Mode for navbar
  binder-web-frontend/src/pages/home/components/navbar/navbar.component.html
  binder-web-frontend/src/pages/home/components/navbar/navbar.component.scss
Labels: bug

#76 feat(webfrontend): Add Transloco to Web Frontend
  binder-web-frontend/package-lock.json
  binder-web-frontend/package.json
  binder-web-frontend/src/app/app.module.ts
  binder-web-frontend/src/app/transloco-root.module.ts
  binder-web-frontend/src/assets/i18n/en.json
  binder-web-frontend/src/pages/home/components/domain-buttons/domain-buttons.component.html
  binder-web-frontend/src/pages/home/components/navbar/navbar.component.html
  binder-web-frontend/src/pages/home/components/table-view/table-view.component.html
  binder-web-frontend/src/pages/home/components/tables-list/tables-list.component.html
  binder-web-frontend/src/pages/pages.module.ts
  binder-web-frontend/transloco.config.js
Labels: feature

#77 Prepare Contribution Guidelines
  CONTRIBUTING.md
Labels: documentation, feature

#75 Create Side Panel component
  binder-web-frontend/src/app/app.component.html
  binder-web-frontend/src/app/app.component.scss
  binder-web-frontend/src/pages/home/components/header/header.component.scss
  binder-web-frontend/src/pages/home/components/side-panel/side-panel.component.html
  binder-web-frontend/src/pages/home/components/side-panel/side-panel.component.scss
  binder-web-frontend/src/pages/home/components/side-panel/side-panel.component.ts
  binder-web-frontend/src/pages/home/home.component.html
  binder-web-frontend/src/pages/home/home.component.scss
  binder-web-frontend/src/pages/pages.module.ts
  binder-web-frontend/src/shared/styles/_variables.scss
Labels: feature

#81 fix(webbackend): Rename Infrastructure layer to Persistence and adjust namespaces
  binder-web-backend/Binder.Api/Binder.Api.csproj
  binder-web-backend/Binder.Api/Program.cs
  binder-web-backend/Binder.Application/Binder.Application.csproj
  binder-web-backend/Binder.Application/Services/DefaultTableService.cs
  binder-web-backend/Binder.IntegrationTests/Binder.IntegrationTests.csproj
  binder-web-backend/Binder.Persistence/Binder.Persistence.csproj
  binder-web-backend/Binder.Persistence/Configurations/AddMySqlConfiguration.cs
  binder-web-backend/Binder.Persistence/Contexts/BinderDbContext.cs
  binder-web-backend/Binder.Persistence/Migrations/20230214211431_InitialMigration.Designer.cs
  binder-web-backend/Binder.Persistence/Migrations/20230214211431_InitialMigration.cs
  binder-web-backend/Binder.Persistence/Migrations/20230411211824_ChangeModelDataToOfficialOnes.Designer.cs
  binder-web-backend/Binder.Persistence/Migrations/20230411211824_ChangeModelDataToOfficialOnes.cs
  binder-web-backend/Binder.Persistence/Migrations/TestDbContextModelSnapshot.cs
  binder-web-backend/Binder.Persistence/Models/Interfaces/IDefaultTableRepository.cs
  binder-web-backend/Binder.Persistence/Repositories/DefaultTableRepository.cs
  binder-web-backend/Binder.UnitTests/Binder.UnitTests.csproj
  binder-web-backend/Binder.UnitTests/Repositories/DefaultTableRepositoryTests.cs
  binder-web-backend/Binder.UnitTests/Services/DefaultTableServiceTests.cs
  binder-web-backend/Binder.sln
Labels: bug

#87 Feature/80 allow web frontend to load apps version from web backend
  binder-web-backend/Binder.Api/Controllers/AppVersionsController.cs
  binder-web-backend/Binder.Api/Program.cs
  binder-web-backend/Binder.Application/Models/Interfaces/IAppVersionService.cs
  binder-web-backend/Binder.Application/Services/AppVersionService.cs
  binder-web-frontend/src/api/api/api.ts
  binder-web-frontend/src/api/api/appVersions.service.ts
  binder-web-frontend/src/api/model/models.ts
  binder-web-frontend/src/pages/home/components/header/header.component.ts
Labels: feature

#93 Add Business Documentation to repo's docs folder
  docs/.gitkeep
  docs/Binder MVP.md
  docs/Binder business requirements.md
  docs/Binder solution architecture documentation.md
Labels: documentation, feature

#94 ref(webbackend): Adjust namespaces in Binder.Persistance/Migrations.
  binder-web-backend/Binder.Persistence/Migrations/20230214211431_InitialMigration.Designer.cs
  binder-web-backend/Binder.Persistence/Migrations/20230214211431_InitialMigration.cs
  binder-web-backend/Binder.Persistence/Migrations/20230411211824_ChangeModelDataToOfficialOnes.Designer.cs
  binder-web-backend/Binder.Persistence/Migrations/20230411211824_ChangeModelDataToOfficialOnes.cs
  binder-web-backend/Binder.Persistence/Migrations/TestDbContextModelSnapshot.cs
Labels: bug

#95 fix(webfrontend): Make button's labels unselectable
  binder-web-frontend/src/pages/home/components/domain-buttons/domain-buttons.component.scss
  binder-web-frontend/src/pages/home/components/navbar/navbar.component.scss
  binder-web-frontend/src/pages/home/components/tables-list/tables-list.component.scss
Labels: bug

#97 fix(webfrontend): Add checkbox in place of boolean text
  binder-web-frontend/src/pages/home/components/table-view/table-view.component.html
  binder-web-frontend/src/pages/pages.module.ts
Labels: bug

#99 fix(webfrontend): Make table list elements clickable
  binder-web-frontend/src/pages/home/components/tables-list/tables-list.component.html
  binder-web-frontend/src/pages/home/components/tables-list/tables-list.component.scss
  binder-web-frontend/src/pages/home/components/tables-list/tables-list.component.ts
Labels: bug
